### ISSUE TITLE
install wifi dongle raspi

### ISSUE THREAD

**Issue by moilerat** [fotonower/chaton#2]
* [x] Done : https://raspberrypihq.com/how-to-add-wifi-to-the-raspberry-pi/ http://www.raspberrypi-france.fr/installer-dongle-wifi/
    - sudo nano /etc/network/interfaces
    - sudo ifdown wlan0
    - sudo ifup wlan0
    - ssh raspberrypi.local

* [ ] https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md  Mdp : Departement de LaRochelle => ne marche pas encore !
   - [ ] Using the Raspberry Pi as an access point to share an internet connection (bridge)

**Comment by HidTosh** [comment]
@moilerat de mon coté j'avais utilisé le lien suivant pour essayer de configurer la wifi 
http://the-raspberry.com/wifi-config

**Comment by martigan** [comment]
j'ai changé les credentials pour le wi-fi pour avoir ceux du WCL
