### ISSUE TITLE
doc for installation raspi

### ISSUE THREAD

**Issue by moilerat** [fotonower/chaton#3]
https://mespotesgeek.fr/fr/variation-de-puissance-electrique-via-raspberry/
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=105044
https://www.raspberrypi.org/forums/viewtopic.php?t=150254
https://fr.pinout.xyz/

![raspberry-pi-pinout](https://user-images.githubusercontent.com/2922559/40031831-c72cd56c-57f1-11e8-990a-1eea4ce414ad.png)

https://www.google.fr/search?q=raspberry+pi+gpio+map&tbm=isch&source=iu&ictx=1&fir=av7XIJ8Zj3OstM%253A%252CcgesJTd0xzUvYM%252C_&usg=__ySlr29sKqZaxaMG-UfnLhdp9aJ0%3D&sa=X&ved=0ahUKEwid2IzawPHaAhUNqaQKHUSmAroQ9QEILTAA#imgrc=av7XIJ8Zj3OstM:
https://www.raspberrypi-spy.co.uk/2012/06/simple-guide-to-the-rpi-gpio-header-and-pins/#prettyPhoto
https://www.pinterest.fr/pin/292804413263273612/?lp=true
https://coolcomponents.co.uk/raspberry-pi?utm_source=post&utm_medium=pinterest&utm_campaign=pinterest
https://github.com/search?q=org%3Afotonower+webcam&type=Issues
https://github.com/fotonower/API/issues/531
https://www.raspberrypi.org/documentation/usage/webcams/README.md
https://raspberrypi.stackexchange.com/questions/4906/control-hardware-pwm-frequency

**Comment by moilerat** [comment]
https://github.com/EParisot/Patate

**Comment by moilerat** [comment]
Ironcar learning : 
http://charlot.fotonower.com:5555/tree/Data_processing/Training
https://theironcar.slack.com/messages/CBCB77ETB/convo/CBCB77ETB-1529846710.000020/
https://docs.google.com/document/d/1jyRhlbmthMA_DuuulYnzUT38okIF_KFZH0a4hh8NCg8/edit#heading=h.aqxqlbrnypzh
[Ironcar - Getting Started Tutorial.pdf](https://github.com/fotonower/chaton/files/2164482/Ironcar.-.Getting.Started.Tutorial.pdf)

**Comment by moilerat** [comment]
https://github.com/SurferTim/documentation/blob/6bc583965254fa292a470990c40b145f553f6b34/configuration/wireless/access-point.md

**Comment by HidTosh** [comment]
```
    6  sudo raspi-config
    7  mkdir workarea
    8  cd workarea/
    9  cd gi
   10  mkdir git
   11  cd git/
   12  ssh-keygen
   13  ls -lt
   14  git clone git@github.com:vinzeebreak/ironcar.git
   15  ls -lt
   16  ssh-add
   17  ssh-agent
   18  ssh-add
   19  `eval ssh-agent`
   20  ssh-add
   21  ssh-add ~/.ssh/id_rsa
   22  ls -lt
   23  git clone git@github.com:vinzeebreak/ironcar.git
   24  cat ~/.ssh/id_rsa
   25  cat ~/.ssh/id_rsa.pub 
   26  git clone git@github.com:vinzeebreak/ironcar.git
   27  ls -lt
   28  cd ironcar/
   29  ls -lt
   30  ./install.sh 

```

**Comment by HidTosh** [comment]
@moilerat  Bug camera raspi ! 

```
pi@raspberrypi:~ $ raspistill -v

raspistill Camera App v1.3.11

Width 3280, Height 2464, quality 85, filename (null)
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Single capture

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Flicker Avoid Mode 'off'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates
```

Le script de prise de photo retourne ça : 

```
script allready launched
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x2340cc0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
script allready launched

```

**Comment by HidTosh** [comment]
ya plus de pbm sur la raspi ! 
Je pense il s'est reglé après que j'ai fait un update et upgrade 

depuis charlot : 

`ssh -i ~/.ssh/id_rsa -p 19991 pi@localhost`

les photos de raspi de wcl sont dans le feed : https://www.fotonower.com/view/1084300
